version: "2"
networks:
  private:
    driver: bridge

services:
  node:
    tty: true
    build: node/
    ports:
      - "3000:80"
    networks:
      - private

  chrome:
    build: chrome/
    networks:
      - private
